name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: make gcc run_tests
      run: make -r TOOLSET=gcc env run_tests
    - name: make clang run_tests
      run: make -r TOOLSET=clang env run_tests
