name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Tests with gcc
      run: make -rj2 TOOLSET=gcc env run_tests
    - name: Tests with clang
      run: make -rj2 TOOLSET=clang env run_tests
