name: Continuous Integrations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        toolset: [gcc, clang]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Boost.Test
      run: sudo apt-get --quiet --yes install libboost-test-dev

    - name: Log environment variables
      run: make -r TOOLSET=${{ matrix.toolset }} env versions

    - name: Build and run unit tests
      run: make -rj2 TOOLSET=${{ matrix.toolset }} example run_tests

    - name: Build and run unit tests with thread sanitizer
      run: make -rj2 TOOLSET=${{ matrix.toolset }} BUILD=sanitize run_tests
